### ISSUE TITLE
Problemas de UX/UI

### ISSUE THREAD

**Issue by matheusgr** [juliobguedes/tormenta#1]
Oi Júlio,

A interface tem alguns problemas que precisam de ação.

Imagino o uso que eu faria na criação de um personagem, ok?

Compensa permitir favoritar/salvar os talentos que o usuário deseja para que depois ele possa ver esses talentos salvos. Então um dos filtros possíveis (e interessantes) seria o por talentos favoritados. Isso ajudaria para uma segunda etapa de escolha/filtros dos talentos.

A idéia de filtrar por classe é legal se o usuário já tem sua classe, e talvez seja um filtro tão importante que talvez mereça destaque de fato. mas talvez ele deseje fazer um filtro mais específico, pela descrição do talento. então, um campo de pesquisa de texto no topo da listagens dos talentos talvez seja algo bom para contribuir. 

Um terceiro problema da UX é a necessidade de entrar em uma nova página para ver a descrição do talento por completo. Um modal permitira pelo menos que o usuário voltasse para a posição anterior em tela. Eu não sou muito fã de modal (particulamente atrapalha o fluxo de execução). Uma alternativa seria permtiir que o talento se expandisse de forma que o usuário pudesse ver e até comparar dois ou três talentos ao mesmo tempo. Uma possibilidade é expandir o próprio row.

Sugiro então:
- [x] Permitir favoritar talentos (e ver talentos favoritados)
- [x] Criar campo de busca textual no topo dos talentos
- [x] Permitir a visualização do talento sem interrupção excessiva do fluxo do usuário (minimamente um modal, idealmente, expansão do card).

**Comment by juliobguedes** [comment]
Implementado :)
